services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --pull --cache-from=alexeldeib/upbound -t alexeldeib/upbound .
  - docker push alexeldeib/upbound