apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: upbound
  name: upbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upbound
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: upbound
    spec:
      containers:
      - image: alexeldeib/upbound
        name: upbound
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: upbound
  name: upbound
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: http
  selector:
    app: upbound
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  generation: 1
  labels:
    app: upbound-app
  name: upbound-app
  namespace: default
spec:
  rules:
  - host: upbound.alexeldeib.xyz
    http:
      paths:
      - backend:
          serviceName: upbound
          servicePort: 80
        path: /
  tls:
  - hosts:
    - upbound.alexeldeib.xyz
    secretName: upbound-tls

